spring:
  #mongodb配置
  data:
    mongodb:
      uri: mongodb://192.168.83.76:27017/db_test
  datasource:
    url: jdbc:mysql:///shirodemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: wsnd
  # Redis数据库索引（默认为0）
  redis:
    database: 9
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: wsnd
      # 连接池最大连接数（使用负值表示没有限制）
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    # 连接池中的最大空闲连接
    # 连接池中的最小空闲连接
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        max-idle: 200
        max-wait:

elasticsearch:
  address: 192.168.89.119:9200
  ip: 192.168.89.119
  port: 9200
  pool: 5
  cluster-name: my-es


