spring:
  datasource:
    url: jdbc:mysql:///shirodemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: wsnd

elasticsearch:
  address: 192.168.89.119:9200
  ip: 192.168.89.119
  port: 9200
  pool: 5
  cluster-name: my-es