spring:
  #mongodb配置
  data:
    mongodb:
      uri: mongodb://192.168.83.76:27017/db_test
  datasource:
    url: jdbc:mysql:///shirodemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: wsnd

elasticsearch:
  address: 192.168.89.119:9200
  ip: 192.168.89.119
  port: 9200
  pool: 5
  cluster-name: my-es


